//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group8_AD_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjustment
    {
        public string VoucherNo { get; set; }
        public int EmpId { get; set; }
        public System.DateTime DateTimeIssued { get; set; }
        public string ItemCode { get; set; }
        public string Reason { get; set; }
        public int QtyChange { get; set; }
        public string Status { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public string ApproverComment { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Item Item { get; set; }
    }
}
