//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group8_AD_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionPoint
    {
        public int ColPtId { get; set; }
        public string Location { get; set; }
        public string Time { get; set; }
        public int ClerkId { get; set; }
    }
}
