//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group8_AD_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public string DeptCode { get; set; }
        public string DeptName { get; set; }
        public string DeptCtcNo { get; set; }
        public string DeptFaxNo { get; set; }
        public Nullable<int> ColPtId { get; set; }
        public Nullable<int> DeptHeadId { get; set; }
        public Nullable<int> DeptRepId { get; set; }
        public Nullable<int> DelegateApproverId { get; set; }
        public Nullable<System.DateTime> DelegateFromDate { get; set; }
        public Nullable<System.DateTime> DelegateToDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
