//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group8_AD_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Adjustments = new HashSet<Adjustment>();
            this.RequestDetails = new HashSet<RequestDetail>();
        }
    
        public string ItemCode { get; set; }
        public string Cat { get; set; }
        public string Desc { get; set; }
        public string Location { get; set; }
        public string UOM { get; set; }
        public bool IsActive { get; set; }
        public int Balance { get; set; }
        public int ReorderLevel { get; set; }
        public int ReorderQty { get; set; }
        public Nullable<int> TempQtyDisb { get; set; }
        public Nullable<int> TempQtyCheck { get; set; }
        public string SuppCode1 { get; set; }
        public Nullable<double> Price1 { get; set; }
        public string SuppCode2 { get; set; }
        public Nullable<double> Price2 { get; set; }
        public string SuppCode3 { get; set; }
        public Nullable<double> Price3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjustment> Adjustments { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Supplier Supplier1 { get; set; }
        public virtual Supplier Supplier2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestDetail> RequestDetails { get; set; }
    }
}
