//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group8_AD_webapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TranId { get; set; }
        public System.DateTime TranDateTime { get; set; }
        public string ItemCode { get; set; }
        public int QtyChange { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public string Desc { get; set; }
        public string DeptCode { get; set; }
        public string SuppCode { get; set; }
        public string VoucherNo { get; set; }
    }
}
